apiVersion: v1
kind: Secret
metadata:
  name: exchange-router-secret
data:
  server_addr: MC4wLjAuMDo4MDgw
  database_url: cG9zdGdyZXM6Ly9yb290OnJvb3RAZXhjaGFuZ2UtcG9zdGdyZXMtc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjgwL2V4Y2hhbmdlLWRi
  redis_url: cmVkaXM6Ly9leGNoYW5nZS1yZWRpcy1zZXJ2aWNlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6ODA=
